#!/bin/bash
# Build a Test Clutch install bundle for deploying on Virtuozzo
# This assumes the availability of GNU shell tools.
set -e
shopt -s extglob  # needed for git scheme check

# git repo with source code
readonly GITREPO="${2:-../testclutch/}"

# git tag/branch/tree-ish of source
readonly TAG="${1:-master}"

# Build bundle for this CPython version
readonly PYVER=3.11

# The target system for which we want to build
readonly TARGETSYS="CPython$PYVER-Linux-x86_64"

# Use these pip package platforms; must be compatible with $TARGETSYS
declare -ar PLATFORMS=(linux_x86_64 manylinux2014_x86_64)

# Get source
test -d build && rm -rf build
mkdir build
mkdir -p tmp$$git/testclutch
if [[ -z "${GITREPO/+([-+_a-zA-Z0-9]):*/}" && "${GITREPO:0:5}" != "file:" ]]; then
    # Looks like a remote git URL with a remote scheme
    # Options to optimize remote git fetching
    readonly GITOPTS=--depth=1
else
    readonly GITOPTS=--shared
fi

git clone --branch "$TAG" $GITOPTS "$GITREPO" tmp$$git/testclutch

test -e testclutch_deploy-commit.txt && mv -f testclutch_deploy-commit.txt testclutch_deploy-commit.txt.old
echo "$(git -C tmp$$git/testclutch rev-parse HEAD)" testclutch > testclutch_deploy-commit.txt

# Start virtual environment to avoid touching system packages (mostly pip)
python3 -m venv .venv-builddeployment
source .venv-builddeployment/bin/activate

# Update local pip first (if necessary); ver. before 23 don't work quite right
python3 -m pip install 'pip>=23'

# Check if the Python version available here matches the run-time
# version needed
if [[ "$(python3 -c "import platform,sys; print(f'{platform.python_implementation()}{sys.version_info.major}.{sys.version_info.minor}-{platform.system()}-{platform.machine()}')")" == "$TARGETSYS" ]]; then
    # We're running on the target system, so we're able to compile modules if necessary.
    # This check is commingling Python bytecode compilation with C extension compilation; the
    # architecture doesn't need to match for the former but does for the latter. Avoiding any
    # kind of compilation is more straightforward, and the run-time savings of bytecode
    # compilation only are likely to be pretty minimal since these are all fairly long-running
    # scripts whose compile times are amortized over long run times.
    echo Python version matches "$TARGETSYS" so compilation is possible
    PIPARCHOPTS=
else
    echo Python version is not "$TARGETSYS" so compilation is not possible
    PIPARCHOPTS="--no-compile --python-version=$PYVER --implementation=cp ${PLATFORMS[*]/#/--platform=} --only-binary=:all:"
fi

python3 -m pip install --disable-pip-version-check --isolated --target="$PWD/build/application/python" $PIPARCHOPTS -r requirements-testclutch.txt tmp$$git/testclutch
test -e testclutch_deploy-requirements.txt && mv -f testclutch_deploy-requirements.txt testclutch_deploy-requirements.txt.old
python3 -m pip list --disable-pip-version-check --isolated --path="$PWD/build/application/python" --format=freeze > testclutch_deploy-requirements.txt
rm -rf tmp$$git

# Fix the shebang at the start of the script which points to a venv python
# which we don't want in the distribution archive
sed -i -e '1s@#!.*$@#!/usr/bin/python3@' build/application/python/bin/*

# Remove dist-info directories, which aren't needed on the target
rm -rf build/application/python/*.dist-info

# Add static files to the install bundle
cp -r --preserve=timestamps distfiles/. build

# Store the highest-valued tag on HEAD to identify this release
# If there is no tag, the file will be empty.
git tag --points-at HEAD | sort -V | tail -1 > testclutch_deploy-tag.txt
cp -p testclutch_deploy-tag.txt build/version.txt

# Build bundle from staging area
tar -C build --xz -cf testclutch_deploy.tar.xz .
rm -rf build

# Deactivate and clean up virtual environment
deactivate
rm -r .venv-builddeployment

echo 'Done: testclutch_deploy.tar.xz'
