# Github Actions configuration
name: Build

permissions: {}

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master and ci branches
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  GITREPO: https://github.com/dfandrich/testclutch.git
  GITBRANCH: master
  DEBIAN_FRONTEND: noninteractive

jobs:
  build_deployment:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: 'install deps'
        run: >
            sudo apt-get update -y &&
            sudo apt-get install -y --no-install-suggests --no-install-recommends
              python3-pip git tidy xz-utils flake8 python3-flake8-builtins
              python3-flake8-comprehensions python3-flake8-deprecated
              python3-flake8-import-order python3-flake8-mutable python3-flake8-quotes &&
            python3 -m pip install --break-system-packages pytype
      - name: 'lint'
        run: |
            flake8 --max-line-length=100 distfiles/*.py distfiles/application/config/testclutchrc
            pytype distfiles/*.py
            tidy -qe distfiles/*.html
            shellcheck --shell=bash -e SC1091 builddeployment distfiles/application/bin/{install-cron-jobs,clean-cache-job,post-deploy,setup-vars}
            shellcheck -e SC1091,SC2086,SC2155 distfiles/application/bin/{comment-pr,incremental-update-job}
      - name: 'build'
        run: ./builddeployment "$GITBRANCH" "$GITREPO"
      - uses: actions/upload-artifact@v4
        with:
          name: testclutch_deploy.tar.xz
          path: testclutch_deploy.tar.xz
          retention-days: ${{ github.ref == 'refs/heads/master' && 30 || 14 }}
      - uses: actions/upload-artifact@v4
        with:
          name: testclutch_deploy.txt
          path: testclutch_deploy-*.txt
          retention-days: ${{ github.ref == 'refs/heads/master' && 90 || 14 }}
