# Github Actions configuration
name: Build

permissions: {}

on:
  # Trigger the workflow on push or pull requests. For pushes, trigger for any push to the
  # ci branch, but only those with a tcc* tag if pushed to the master (or other) branch.
  push:
    branches:
      - ci
    tags:
      - tcc*
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  GITREPO: https://github.com/dfandrich/testclutch.git
  GITBRANCH: master
  DEBIAN_FRONTEND: noninteractive

jobs:
  build_deployment:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          # This is buggy and causes an error when the triggering condition is a tag. Since the
          # triggering tag is already fetched and available for reference, it's fine to leave this
          # at the default false.
          # https://github.com/actions/checkout/issues/1467
          # fetch-tags: true
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # Basing the key on only the testclutch requirements means that any updates to pip
          # packages & dependencies installed in this workflow (i.e. pytype) won't be cached.
          # This is suboptimal but not really worth trying to fix.
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-testclutch.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: 'install deps'
        run: >
            sudo apt-get update -y &&
            sudo apt-get install -y --no-install-suggests --no-install-recommends
            python3-pip git tidy xz-utils flake8 python3-flake8-builtins
            python3-flake8-comprehensions python3-flake8-deprecated python3-flake8-docstrings
            python3-flake8-import-order python3-flake8-mutable python3-flake8-noqa
            python3-flake8-quotes &&
            python3 -m pip install --break-system-packages pytype
      - name: 'lint'
        run: |
            flake8 --max-line-length=100 --ignore=D100,D103,W503 distfiles/*.py distfiles/application/config/testclutchrc
            pytype distfiles/*.py scripts/*.py
            tidy -qe distfiles/*.html
            shellcheck --shell=bash -e SC1091 builddeployment distfiles/application/bin/{install-cron-jobs,clean-cache-job,post-deploy,setup-vars}
            shellcheck -e SC1091,SC2086 distfiles/application/bin/{comment-pr,incremental-update-job}
            shellcheck -e SC2016 scripts/delete-subset-logs scripts/plot-job-times
      - name: 'build'
        run: ./builddeployment "$GITBRANCH" "$GITREPO"
      - uses: actions/upload-artifact@v4
        with:
          name: testclutch_deploy.tar.xz
          path: testclutch_deploy.tar.xz
          retention-days: ${{ github.ref == 'refs/heads/master' && 30 || 14 }}
      - uses: actions/upload-artifact@v4
        with:
          name: testclutch_deploy.txt
          path: testclutch_deploy-*.txt
          retention-days: ${{ github.ref == 'refs/heads/master' && 90 || 14 }}
